### PR TITLE
Use Redis caching for Flickr API requests

### LINKED ISSUE #212: Use Redis to cache Flickr results

### PR DESCRIPTION
**Pull request by abuddiga**
#### What's this PR do?
- Uses Redis to cache Flickr location/event requests
- Modularizes Redis interaction functions into `utils` folder
#### What are the relevant tickets/issues?

Closes #212 
#### Where should the reviewer start?

`flickrSearch.js`
#### Questions:
- Does this add new dependencies?
- Does our documentation need to be updated?

### CODE REVIEW

**Comment by xuejinglu** [comment]
:gem: :pig:

**Comment by leranf** [comment]
💎

**Comment by leranf** [comment]
❤️

**Comment by boyajay** [comment]
:tiger:  beastmode

**Pull request merged**
