### PR TITLE
real trip data

### LINKED ISSUE #137: Get all trips

### PR DESCRIPTION
**Pull request by leranf**
#### What's this PR do?
- pulls real data from db to populate my trips page
#### What are the relevant tickets/issues?

closes #137 
closes #160 
#### Screenshots (if appropriate)

screen shot 2016-03-26 at 11 17 12 am
#### Questions:
- Does this add new dependencies?
- Does our documentation need to be updated?

### CODE REVIEW

**Comment by boyajay** [comment]
:sick: sick brah

**Comment by boyajay** [comment]
:mask: sick brah

**Comment by xuejinglu** [comment]
:+1: :game_die: :gem:

**Comment by abuddiga** [comment]
:computer:

**Pull request merged**
